package pl.michuu93.prescriptions.exception;

enum ApiErrorCode {
    UNKNOWN_ERROR, DATABASE_UNAVAILABLE, INVALID_XML_JSON, UNSUPPORTED_MEDIA_TYPE, METHOD_NOT_ALLOWED, NO_SUCH_ELEMENT, INVALID_BIRTHDATE, INVALID_PESEL, INVALID_LICENSE
}