server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi.enabled: ALWAYS
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    guru.springframework.controllers: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    pl.michuu93: DEBUG