spring:
  profiles:
    active: dev

---

server:
  port: 8080

spring:
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi.enabled: ALWAYS
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    guru.springframework.controllers: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    pl.michuu93: DEBUG


---

server:
  port: 80

spring:
  profiles: docker
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi.enabled: ALWAYS
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR
    guru.springframework.controllers: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    pl.michuu93: ERROR